### ISSUE TITLE
Docker导入问题

### ISSUE THREAD

**Issue by Dev-Wiki** [mebtte/cicada#114]
nas上使用docker compose 安装
```yaml
version: "3"
services:
  cicada:
    restart: always
    container_name: cicada
    image: mebtte/cicada:v2

    # user mapping
    # user: 1000:1000

    command: start --port 8000 --data /data
    ports:
      - 19999:8000
    volumes:
      - ./data:/data
      - /share/MultimediaExtend/Music/:/source
```

可以使用 `/share/MultimediaExtend/Music:/source` 配置文件夹么? 配置以后还是找不到音乐文件
![image](https://github.com/mebtte/cicada/assets/12946956/85934adf-d1aa-4ba8-9538-732d2891842c)

![image](https://github.com/mebtte/cicada/assets/12946956/f8840ad1-0799-4739-b168-c03a27883070)

**Comment by mebtte** [comment]
卷映射有问题, 可以改成这样:
```yml
command: start --port 8000 --data /source
volumes:
    - /share/MultimediaExtend/Music:/source
```

**Comment by Dev-Wiki** [comment]
> 卷映射有问题, 可以改成这样:
> 
> ```yaml
> command: start --port 8000 --data /source
> volumes:
>     - /share/MultimediaExtend/Music:/source
> ```

包含data的话是这样么:

```yaml
command: start --port 8000 --data /data /source
volumes:
    - ./data:/data
    - /share/MultimediaExtend/Music:/source
```
还是不用带 /data 和你回复的一样? 我尝试一下

**Comment by mebtte** [comment]
`--data /data` 指的是数据存放的目录, 只能是一个参数, 而不能是 `--data /data /source`, 所以下面的配置只能二选一:
```yml
command: start --port 8000 --data /data
volumes:
    - ./data:/data
```
```yml
command: start --port 8000 --data /source
volumes:
    - /share/MultimediaExtend/Music:/source
```

**Comment by Dev-Wiki** [comment]
如果不指定 ./data:/data 那就按照 docker的 默认是吧, 希望能支持直接读取 volumes配置 或者支持同时配置

**Comment by mebtte** [comment]
> 如果不指定 ./data:/data 那就按照 docker的 默认是吧, 希望能支持直接读取 volumes配置 或者支持同时配置

1. docker 默认是指什么
2. 对于 docker 内的应用来说是无法感知 volumes 的, 所以`读取 volumes 配置`是无法实现的

**Comment by Dev-Wiki** [comment]
改为指定source 仍然无法获取音乐：
![image](https://github.com/mebtte/cicada/assets/12946956/c2fbc679-75c7-4d24-9f39-1f775c23b440)

```yaml
version: "3"
services:
  cicada:
    restart: always
    container_name: cicada
    image: mebtte/cicada:v2

    # user mapping
    # user: 1000:1000

    command: start --port 8000 --data /source
    ports:
      - 19999:8000
    volumes:
      - /share/MultimediaExtend/Music:/source
```

![image](https://github.com/mebtte/cicada/assets/12946956/c7e8e6e6-1308-41e1-b2b4-8298ac3550f5)

**Comment by Dev-Wiki** [comment]
这个文件夹位置应该是对的， 我部署 navidrome 时能正常读取显示：
```yaml
version: "3"
services:
  navidrome:
    image: deluan/navidrome
    ports:
      - "4533:4533"
    restart: unless-stopped
    environment:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info  
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
    volumes:
      - "./data:/data"
      - "/share/MultimediaExtend/Music:/music:ro"
```
