### ISSUE TITLE
容器内使用cicada import 似乎有文件权限问题？

### ISSUE THREAD

**Issue by coracoo** [mebtte/cicada#138]
我使用绿联DXP 4800 Plus创建容器目录

docker-compose如下
```
services:
  cicada:
    restart: always
    container_name: cicada
    image: mebtte/cicada:v2
    command: start --port 8000 --data /data
    ports:
      - 18888:8000
    volumes:
      - ./data:/data
      - /volume2/音乐:/source:ro
```

🔻在data目录下新建了一个music目录
![Image](https://github.com/user-attachments/assets/982bb9cc-270c-4e65-a3e5-fc4dc334e992)

🔻NAS目录下的音乐文件
![Image](https://github.com/user-attachments/assets/71394c5f-2d39-40a3-913c-ef35f76d4396)

🔻映射到容器后，查询到的文件
![Image](https://github.com/user-attachments/assets/a2b0699b-eee2-41bb-b33e-03dd1aef2508)

🔻使用`cicada import --data /data/music --recursive /source`报错信息如下

![Image](https://github.com/user-attachments/assets/5273f91f-eb33-4099-9ad3-995740c417d5)
